# Generated by Django 2.2.10 on 2020-04-16 06:44

import apps.utils.images.uploads_images
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('slug_name', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'precio',
                'verbose_name_plural': 'precios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('slug_name', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.Category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'subcategoria',
                'verbose_name_plural': 'subcategorias',
                'ordering': ['-created'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductWithoutPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('slug_name', models.SlugField(blank=True, max_length=255, unique=True)),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Código interno')),
                ('barcode', models.CharField(max_length=30, unique=True, verbose_name='Código de barras')),
                ('name', models.CharField(max_length=210, verbose_name='Nombre')),
                ('desc', models.CharField(max_length=255, verbose_name='Descripción')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('stock_min', models.PositiveIntegerField(default=0, verbose_name='Stock mínimo')),
                ('stock_max', models.PositiveIntegerField(blank=True, default=0, verbose_name='Stock máximo')),
                ('picture', models.ImageField(blank=True, upload_to=apps.utils.images.uploads_images.custom_upload_to, verbose_name='Imagen')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventories.SubCategory', verbose_name='Subcategoria')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('slug_name', models.SlugField(blank=True, max_length=255, unique=True)),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Código interno')),
                ('barcode', models.CharField(max_length=30, unique=True, verbose_name='Código de barras')),
                ('name', models.CharField(max_length=210, verbose_name='Nombre')),
                ('desc', models.CharField(max_length=255, verbose_name='Descripción')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('stock_min', models.PositiveIntegerField(default=0, verbose_name='Stock mínimo')),
                ('stock_max', models.PositiveIntegerField(blank=True, default=0, verbose_name='Stock máximo')),
                ('picture', models.ImageField(blank=True, upload_to=apps.utils.images.uploads_images.custom_upload_to, verbose_name='Imagen')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Precio')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventories.SubCategory', verbose_name='Subcategoria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductProxi',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Stocks de productos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventories.product',),
        ),
        migrations.CreateModel(
            name='ProductWithoutPriceProxi',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Stocks de productos sin precios',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventories.productwithoutprice',),
        ),
        migrations.CreateModel(
            name='PriceWithDesc',
            fields=[
                ('price_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventories.Price')),
                ('desc', models.CharField(max_length=210, verbose_name='Tipo de precio')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.ProductWithoutPrice')),
            ],
            options={
                'verbose_name': 'precio con descripcion',
                'verbose_name_plural': 'precios con descripcion',
                'ordering': ['desc'],
            },
            bases=('inventories.price',),
        ),
    ]
