# Generated by Django 2.2.10 on 2020-04-21 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0002_auto_20200421_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('personfiscal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persons.PersonFiscal')),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'personas',
                'ordering': ['last_name', 'first_name'],
                'abstract': False,
            },
            bases=('persons.personfiscal',),
        ),
    ]
