# Generated by Django 2.2.10 on 2020-04-21 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'proveedor', 'verbose_name_plural': 'proveedores'},
        ),
    ]
