# Generated by Django 2.2.10 on 2020-04-25 05:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
        ('purchases', '0002_auto_20200421_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('number_purchase', models.CharField(blank=True, max_length=18, null=True, verbose_name='Número interno')),
                ('date_purchase', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('invoice_num', models.CharField(blank=True, max_length=30, null=True, verbose_name='Observaciones')),
                ('is_fiscal', models.BooleanField(default=True, verbose_name='Es fiscal')),
                ('invoic_date', models.DateField(verbose_name='Fecha de la factura de compra')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_choices', models.CharField(blank=True, choices=[('0 %', 0.0), ('21 %', 0.21), ('10.5 %', 0.105)], default='0 %', max_length=2, null=True, verbose_name='IVA')),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.Supplier')),
            ],
            options={
                'verbose_name': 'compra',
                'verbose_name_plural': 'compras',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ItemPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('supplier_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.FloatField(default=0, verbose_name='Cantidad')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.Product', verbose_name='Producto')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.Purchase', verbose_name='Compra')),
            ],
            options={
                'verbose_name': 'item compra',
                'verbose_name_plural': 'item compras',
                'ordering': ['id'],
            },
        ),
    ]
