# Generated by Django 2.2.10 on 2020-04-25 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_itempurchase_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempurchase',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventories.Product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='invoice_num',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='N° de factura'),
        ),
    ]
