# Generated by Django 2.2.10 on 2020-04-25 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_auto_20200425_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempurchase',
            name='active',
        ),
    ]
