# Generated by Django 2.2.10 on 2020-05-02 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0008_auto_20200430_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempurchase',
            old_name='supplier_price',
            new_name='price',
        ),
    ]
