# Generated by Django 2.2.10 on 2020-04-19 06:09

import apps.utils.images.uploads_images
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('slug_name', models.SlugField(blank=True, max_length=255, unique=True)),
                ('fiscal_code', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='CUIT')),
                ('name', models.CharField(max_length=210, verbose_name='Nombre')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Inicio de actividades')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('movile', models.CharField(blank=True, max_length=50, null=True, verbose_name='Celular')),
                ('telephone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('picture', models.ImageField(blank=True, upload_to=apps.utils.images.uploads_images.custom_upload_to, verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresa',
                'ordering': ['name'],
            },
        ),
    ]
